<h1><center>Лабораторна робота 1.</center></h1>
<h2><center>Аналіз доходу населення за набором даних Adult Data Set</center></h2>

**Виконав:** Березюк М.В.

**Варіант:** № 4

<a class="anchor" id="lab-1"></a>

## Зміст

1. [Завантаження і знайомство з даними](#lab-1.1)
2. [Варіанти завдань до лабораторної роботи](#lab-1.2)

<a class="anchor" id="lab-1.1"></a>

## <span style="color:blue; font-size:1.2em;">1.1. Завантаження та підготовка даних</span>

[Повернутися до змісту](#lab-1)

У лабораторній роботі пропонується за допомогою Pandas відповісти на кілька запитань за набором даних [Adult](https://archive.ics.uci.edu/ml/datasets/adult) сховища UCI.

Унікальні значення ознак набору даниз Adult Data Set (більше інформації в описі [Adult](https://archive.ics.uci.edu/ml/datasets/adult)):

- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

Завантажимо `Pandas` та переглянемо вміст набору даних.

In [1]:
import pandas as pd

In [2]:
adult_data_url = 'https://raw.githubusercontent.com/radiukpavlo/intelligent-data-analysis/main/02_assignments/ida_lab-01_adult_pandas/adult.data.csv'

data = pd.read_csv(adult_data_url)
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

-----
<a class="anchor" id="lab-1.2"></a>

## <span style="color:blue; font-size:1.2em;">1.2. Варіанти завдань до лабораторної роботи</span>

[Повернутися до змісту](#lab-1)

Варіанти завдань відповідають списку студентв групі. Дайте відповіді на запитання з використанням бібліотеки `Pandas`.

***Примітка 1:*** вища освіта відповідає значенням ознаки *education* - Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters або Doctorate)

***Примітка 2:*** одруженими вважаємо тих, у кого *marital-status* починається з *Married* (Married-civ-spouse, Married-spouse-absent або Married-AF-spouse), інших вважаємо холостими.

### <span style="color:red; font-size:1.5em;">Завдання 1</span>

**Варіант 1:**
Знайдіть кількість осіб, які заробляють понад 50K (*salary*).

**Варіант 2:**
Яка середня *capital-loss* для осіб, які заробляють менше 50K (*salary*)?

**Варіант 3:**
Який середній *age* осіб у наборі даних?

**Варіант 4:**
Скільки осіб зареєстровано як працівники *Private* сектора (*workclass*)?

**Варіант 5:**
Яка загальна кількість унікальних *occupations* у наборі даних?

**Варіант 6:**
Скільки чоловіків (*sex*) зареєстровано в наборі даних UCI Adult?

**Варіант 7:**
Обчисліть середню кількість *hours-per-week* для осіб, які працюють у *Self-employed* секторі.

**Варіант 8:**
Скільки осіб мають *capital-gain* понад нуля?

**Варіант 9:**
Який мінімальний *age* осіб, які працюють понад 40 *hours-per-week*?

**Варіант 10:**
Знайдіть загальну кількість осіб з *United-States* (*native-country*).

**Варіант 11:**
Скільки осіб мають значення *education-num* більш як 10?

**Варіант 12:**
Скільки жінок (*sex*) є в наборі даних UCI Adult?

**Варіант 13:**
Обчисліть максимальний *capital-gain* для осіб в *Exec-managerial* професії.

**Варіант 14:**
Скільки осіб зареєстровано як одружені (*marital-status*)?

**Варіант 15:**
Яка найпоширеніша *occupation* поміж осіб із *salary* понад 50K?

**Варіант 16:**
Знайдіть середній *age* осіб з *capital-loss* понад нуля.

**Варіант 17:**
Скільки осіб мають рівень *education* зі значенням *Bachelors*?

**Варіант 18:**
Яка загальна кількість осіб, які працюють понад 40 *hours-per-week*?

**Варіант 19:**
Знайдіть кількість осіб, які заробляють менше 50K і працюють у *Private* секторі.

**Варіант 20:**
Обчисліть середній *age* осіб, зареєстрованих як *Divorced* (*marital-status*).

In [3]:
data[data['workclass'] == 'Private'].shape[0]

22696

### <span style="color:red; font-size:1.5em;">Завдання 2</span>

**Варіант 1:**
Яка частка громадян Мексики (у%, *native-country*) у наборі даних?

**Варіант 2:**
Яке середнє значення і середньоквадратичне відхилення віку тих, хто отримує зарплату понад 50K на рік (ознака *salary*)?

**Варіант 3:**
Знайдіть середній та медіанний вік (*age*) осіб, які мають докторський ступінь (*education*).

**Варіант 4:**
Згрупуйте дані за *education* та обчисліть середню кількість *hours-per-week*, відпрацьованих кожною групою за рівнем освіти.

**Варіант 5:**
Який розподіл сімейного стану (*marital-status*) поміж осіб, які заробляють понад 50K на рік (*salary*)? Використайте функцію `value_counts()`.

**Варіант 6:**
Обчисліть мінімальну, максимальну та середню кількість робочих годин на тиждень (*hours-per-week*) для осіб, які працюють як *workclass*.

**Варіант 7:**
Визначте середній *age* осіб із Німеччини (*native-country*) у наборі даних. Використайте функцію `loc[]` для фільтрації.

**Варіант 8:**
Створіть новий стовпець, який категоризує осіб як *Young*, якщо їхній *age* менш як 30 років, і *Old*, якщо їхній *age* 30 років або більше. Порахуйте, скільки осіб потрапляє в кожну категорію.

**Варіант 9:**
Який середній рівень доходу (*salary*) для різних вікових груп (наприклад, 20–30, 30–40 років тощо)? Використайте функцію `cut()` для створення вікових інтервалів і згрупуйте дані за цими інтервалами.

**Варіант 10:**
З’ясуйте, скільки осіб працювало понад 40 годин на тиждень (*hours-per-week*) та має заробіток понад 50K (*salary*).

**Варіант 11:**
Відфільтруйте осіб, які працюють менше ніж 30 годин на тиждень (*hours-per-week*) і відобразіть середнє значення та стандартне відхилення їхнього *age*.

**Варіант 12:**
Визначте найпоширенішу професію (*occupation*) поміж людей старше 50 років (*age*). Використайте функцію `mode()`.

**Варіант 13:**
Знайдіть кількість осіб, які перебувають у шлюбі (*marital-status*) і працюють у сфері *Tech-support* або *Exec-managerial* (*occupation*).

**Варіант 14:**
Яка середня кількість годин, відпрацьованих на тиждень (*hours-per-week*) людьми з рівнем освіти *Bachelors* (*education*) і доходом менше ніж 50K (*salary*)?

**Варіант 15:**
Створіть зведену таблицю, яка показує середній *age* осіб на основі їхньої країни походження (*native-country*) та виду зайнятості (*workclass*).

**Варіант 16:**
Скільки осіб ніколи не були одруженими (*marital-status*) і мають рівень освіти *Master* або вище (*education*)? Використайте функцію `query()` для фільтрації даних.

**Варіант 17:**
Знайдіть частку осіб, які заробляють понад 50K (*salary*) поміж різних вікових груп (наприклад, 20–30, 30–40 років тощо). Використайте функції `groupby()` та `size()` для обчислення відсотків.

**Варіант 18:**
Використовуючи функцію `groupby()`, обчисліть середнє значення *education-num* для осіб, які працюють у *Private* та *Self-emp-inc* секторах зайнятості (*workclass*).

**Варіант 19:**
Який відсоток осіб зі *United States* (*native-country*), що заробляють понад 50K (*salary*)? Використайте функцію `loc[]` для фільтрації та обчисліть відсоток.

**Варіант 20:**
Створіть стовпчасту діаграму, що показує розподіл рівнів освіти (*education*) поміж людей, які працюють понад 40 годин на тиждень (*hours-per-week*). Використайте функції `value_counts()` та `plot()`.

In [4]:
data.groupby(['education'])['hours-per-week'].mean()

education
10th            37.052519
11th            33.925957
12th            35.780600
1st-4th         38.255952
5th-6th         38.897898
7th-8th         39.366873
9th             38.044747
Assoc-acdm      40.504217
Assoc-voc       41.610709
Bachelors       42.614006
Doctorate       46.973366
HS-grad         40.575374
Masters         43.836332
Preschool       36.647059
Prof-school     47.425347
Some-college    38.852284
Name: hours-per-week, dtype: float64

### <span style="color:red; font-size:1.5em;">Завдання 3</span>

**Варіант 1:**
Яка частка людей у наборі даних молодших за 20 років? Відфільтруйте набір даних за стовпцем *age* і використайте `value_counts(normalize=True)`.

**Варіант 2:**
Яка середня кількість робочих годин на тиждень для людей із дипломом бакалавра? Відфільтруйте за *education* і використайте `mean()`.

**Варіант 3:**
Скільки осіб у наборі даних заробляють понад 50K і перебувають у шлюбі? Використайте *salary* і `len()` для підрахунку результатів.

**Варіант 4:**
Який медіанний вік осіб, які працюють понад 40 годин на тиждень? Використайте *hours-per-week* і `median()`.

**Варіант 5:**
Обчисліть загальну кількість людей, які належать до різних професій (*occupation*), згрупованих за расою (*race*). Використайте `groupby`.

**Варіант 6:**
Знайдіть найпоширенішу професію (*occupation*) поміж людей, які заробляють менше ніж 50K Відфільтруйте за *salary* і використайте `mode()`.

**Варіант 7:**
Яка частка людей старше 60 років працює менше ніж 30 годин на тиждень? Відфільтруйте за *age* і *hours-per-week* та використайте `len()`.

**Варіант 8:**
Скільки людей у наборі даних ніколи не були одруженими? Використайте `value_counts()`.

**Варіант 9:**
Яке стандартне відхилення кількості годин на тиждень для людей із вищою освітою? Відфільтруйте за *education* для вищих ступенів і використайте `std()`.

**Варіант 10:**
Визначте кількість людей у кожній країні походження, які заробляють понад 50K Відфільтруйте за *salary* і використайте `groupby`.

**Варіант 11:**
Який мінімальний *age* людей, які розлучені та заробляють понад 50K? Відфільтруйте за *marital-status* і використайте `min()`.

**Варіант 12:**
Обчисліть середню кількість годин на тиждень для людей, згрупованих за рівнем освіти. Використайте `groupby` для визначення середньої кількості годин на тиждень для кожного рівня освіти.

**Варіант 13:**
Який відсоток осіб є самозайнятими? Відфільтруйте за *workclass* і використайте `value_counts(normalize=True)`.

**Варіант 14:**
Яка раса має найвищий середній *age*? Використайте `groupby` для обчислення середнього віку за расою та визначте максимальне значення.

**Варіант 15:**
Яка максимальна кількість годин на тиждень, яку працюють жінки? Відфільтруйте за *sex* і використайте `max()`.

**Варіант 16:**
Який відсоток людей із доходом менше або рівним 50K працюють у приватному секторі? Відфільтруйте за *salary* і *workclass*.

**Варіант 17:**
Скільки людей працюють на керівних посадах і мають післяшкільну освіту? Відфільтруйте за *occupation* і *education* для вищих ступенів, а потім підрахуйте за допомогою `len()`.

**Варіант 18:**
Визначте частку осіб із середньою освітою або вище, які працюють менше ніж 40 годин на тиждень. Відфільтруйте за *education* і *hours-per-week*, а потім обчисліть співвідношення.

**Варіант 19:**
Який середній вік людей, які працюють на уряд і заробляють понад 50K? Відфільтруйте за *workclass* і *salary* і використайте `mean()`.

**Варіант 20:**
Знайдіть загальну кількість одружених осіб, які ніколи не працювали в приватному (*Private*) секторі. Відфільтруйте за *marital-status* і *workclass* і використайте `count()` для визначення результату.

In [5]:
data[data['hours-per-week'] > 40]['age'].median()

39.0

### <span style="color:red; font-size:1.5em;">Завдання 4</span>

**Варіант 1:**
Обчисліть середню кількість робочих годин на тиждень (*hours-per-week*) для чоловіків із раси *Black* і порівняйте її з відповідним значенням для жінок.

**Варіант 2:**
Визначте найпоширенішу професію (*occupation*) для жінок старше 40 років із раси *White*.

**Варіант 3:**
З’ясуйте, який рівень освіти має найбільший відсоток осіб, що заробляють понад 50K на рік, згрупованих за расою.

**Варіант 4:**
Обчисліть медіанний *age* одружених чоловіків (*marital-status*, починаючи з *Married*) і порівняйте його з неодруженими чоловіками, згрупованими за расою.

**Варіант 5:**
Визначте расу з найвищим середнім рівнем освіти (*education-num*) поміж осіб, які працюють понад 40 годин на тиждень.

**Варіант 6:**
Обчисліть відсоток осіб зі ступенем *Doctorate*, які заробляють понад 50K, і порівняйте його з особами зі ступенем *Bachelors*.

**Варіант 7:**
З’ясуйте, яка категорія сімейного стану має найбільшу кількість осіб у професії *Exec-managerial*.

**Варіант 8:**
Визначте середній вік осіб у класі зайнятості *Self-emp-not-inc* і порівняйте його з тими, хто працює у *Private* секторі.

**Варіант 9:**
Визначте расу та стать осіб, які мають найбільшу середню кількість робочих годин на тиждень (*hours-per-week*) поміж тих, хто заробляє понад 50K.

**Варіант 10:**
Використайте *capital-gain* для обчислення загального капітального прибутку для осіб віком від 30 до 50 років, згрупованих за статтю та расою.

**Варіант 11:**
Обчисліть моду (найчастіше значення) класу зайнятості для осіб зі ступенем *Masters*, які заробляють менше або рівно 50K.

**Варіант 12:**
Згрупуйте осіб за расою та сімейним станом і обчисліть стандартне відхилення їхнього віку для тих, хто заробляє понад 50K.

**Варіант 13:**
Знайдіть расу з найбільшою кількістю осіб у професії *Tech-support*, які заробляють менше ніж 50K.

**Варіант 14:**
Використайте *hours-per-week* для обчислення 25-го перцентиля робочих годин для осіб зі ступенем *Bachelors*.

**Варіант 15:**
З’ясуйте, який рівень освіти має найбільшу дисперсію у віці, згруповану за статтю та расою.

**Варіант 16:**
Обчисліть кореляцію між віком і робочими годинами на тиждень для осіб у професії *Sales*.

**Варіант 17:**
Визначте, яка група сімейного стану має найбільшу частку осіб із капітальними втратами більш як 0.

**Варіант 18:**
Згрупуйте осіб за расою та обчисліть середню кількість робочих годин на тиждень для тих, хто заробляє понад 50K і менше або рівно 50K. Порівняйте результати.

**Варіант 19:**
Визначте вікову групу (до 30, 30–50, понад 50 років), яка має найбільшу частку осіб у професії *Adm-clerical*.

**Варіант 20:**
Використайте стовпці *marital-status* і *sex* для обчислення середнього капітального прибутку та капітальних втрат для одружених і неодружених чоловіків та жінок відповідно.

In [6]:
male = data[data['sex'] == 'Male']
married_mens = male[male['marital-status'].str.startswith('Married')]
unmarried_mens = male[~male['marital-status'].str.startswith('Married')]
median_age_married = married_mens.groupby('race')['age'].median()
median_age_unmarried = unmarried_mens.groupby('race')['age'].median()

print("Медіанний вік одружених чоловіків за расою:", median_age_married)
print("\nМедіанний вік неодружених чоловіків за расою:", median_age_unmarried)

Медіанний вік одружених чоловіків за расою: race
Amer-Indian-Eskimo    41.0
Asian-Pac-Islander    42.0
Black                 43.0
Other                 38.0
White                 42.0
Name: age, dtype: float64

Медіанний вік неодружених чоловіків за расою: race
Amer-Indian-Eskimo    31.0
Asian-Pac-Islander    27.0
Black                 30.0
Other                 28.0
White                 29.0
Name: age, dtype: float64

### <span style="color:red; font-size:1.5em;">Завдання 5</span>

**Варіант 1:**
Порахуйте, скільки осіб у наборі даних перебувають у шлюбі, і визначте відсоток із них, які заробляють понад 50K. Використайте `groupby()` за стовпцем `marital-status` і застосуйте функцію `size()` для підрахунку.

**Варіант 2:**
Обчисліть середнє, медіанне та стандартне відхилення *hours-per-week* для кожного рівня освіти (*education*) і дізнайтеся, як ці значення відрізняються між особами, які заробляють більш як 50K та менше або рівно 50K Використайте `groupby()` і `agg()`.

**Варіант 3:**
Визначте 5 найпоширеніших професій (`occupation`) поміж людей, які працюють понад 40 годин на тиждень, і дізнайтеся, який відсоток із них заробляє понад 50K. Використайте `value_counts()` і фільтрацію.

**Варіант 4:**
Обчисліть загальну кількість відпрацьованих годин на тиждень для кожної раси (*race*) і визначте групу з найбільшою загальною кількістю робочих годин. Використайте `groupby()` і `sum()` для стовпця *hours-per-week*.

**Варіант 5:**
Визначте найпоширенішу професію (*occupation*) поміж людей старше 40 років і обчисліть середній дохід для цієї групи. Використайте `groupby()` і `mean()`.

**Варіант 6:**
Для кожної статі (*sex*) обчисліть середній і медіанний дохід, відфільтрувавши осіб із дипломом бакалавра. Використайте `loc[]`, `groupby()` і `agg()`.

**Варіант 7:**
Знайдіть відсоток осіб у кожному класі зайнятості (*workclass*), які працюють мінімальну кількість годин на тиждень. Використайте `groupby()` і `min()`.

**Варіант 8:**
Проаналізуйте взаємозв’язок між віком і робочими годинами, обчисливши коефіцієнт кореляції між *age* та *hours-per-week*. Використайте функцію `corr()`.

**Варіант 9:**
Для осіб, які працюють понад 50 годин на тиждень, визначте три країни (*native-country*) з найбільшою кількістю представників. Використайте `value_counts()` і фільтрацію.

**Варіант 10:**
Обчисліть медіанну кількість *hours-per-week* для кожного сімейного стану (*marital-status*) і визначте, яка група працює найбільше годин у середньому. Використайте `groupby()` і `median()`.

**Варіант 11:**
Для осіб, які заробляють понад 50K, знайдіть найпоширеніший рівень освіти (*education*) й обчисліть середню кількість відпрацьованих годин для цієї групи. Використайте `groupby()` і `mean()`.

**Варіант 12:**
Обчисліть відсоток осіб, які заробляють понад 50K, для кожної статі (*sex*), і порівняйте цей відсоток поміж різних рас. Використайте `groupby()` і `size()`.

**Варіант 13:**
Визначте середню кількість відпрацьованих годин на тиждень для осіб із середньою освітою, згрупованих за сімейним станом. Використайте `groupby()` і `mean()`.

**Варіант 14:**
З’ясуйте, яка професія має найвищий відсоток осіб, які заробляють понад 50K. Використайте `groupby()` і `apply()`.

**Варіант 15:**
Обчисліть частку осіб із кожної країни (*native-country*), які працюють менше ніж 30 годин на тиждень. Використайте `groupby()` і `size()` з фільтрацією.

**Варіант 16:**
Проаналізуйте розподіл робочих годин для осіб, які ніколи не були одруженими, згрупованих за професіями. Використайте `groupby()` і `describe()`.

**Варіант 17:**
Для кожного рівня освіти обчисліть середню кількість робочих годин для осіб віком від 30 до 50 років. Використайте `loc[]`, `groupby()` і `mean()`.

**Варіант 18:**
Знайдіть гендерний розподіл для осіб, які працюють понад 60 годин на тиждень, й обчисліть середній дохід для кожної групи. Використайте `groupby()` і `mean()`.

**Варіант 19:**
Порівняйте середню кількість робочих годин осіб із різних рас, які перебувають у шлюбі та заробляють понад 50K. Використайте `groupby()` і `agg()`.

**Варіант 20:**
Знайдіть найпоширенішу професію для осіб, які працюють менше ніж 20 годин на тиждень, й обчисліть їхній середній вік. Використайте `groupby()` і `mean()`.

In [7]:
total_number_hours = data.groupby(['race'])['hours-per-week'].sum()
print(total_number_hours)
print("\nРаса з найбільшою загальною кількістю робочих годин:", total_number_hours.idxmax())

race
Amer-Indian-Eskimo      12455
Asian-Pac-Islander      41692
Black                  120033
Other                   10696
White                 1131808
Name: hours-per-week, dtype: int64

Раса з найбільшою загальною кількістю робочих годин: White